Repository DevWars/devwars-api, pull requests merged in 2020-01, with the labels that each got.

#29 Email Permissions Support
  app/controllers/Email.controller.ts
  app/controllers/game/GameApplication.controller.ts
  app/controllers/user/LinkedAccount.controller.ts
  app/mail/game-application-resign.mjml
  app/mail/layouts/unsubscribe.mjml
  app/mail/linked-account-disconnect.mjml
  app/mail/linked-account.mjml
  app/models/EmailOptIn.ts
  app/models/User.ts
  app/repository/EmailOptIn.repository.ts
  app/repository/GameApplication.repository.ts
  app/request/IUpdateEmailPermissionRequest.ts
  app/routes/User.routes.ts
  app/routes/validators/email.validator.ts
  app/seeding/EmailOptIn.seeding.ts
  app/services/Auth.service.ts
  app/services/Mail.service.ts
  cli/Seeder.ts
  migration/1576947482396-EmailPermissionGeneration.ts
  ormconfig.json
  package.json
  test/email.test.ts
Labels: enhancement

#36 Api-docs for profile: get - /users/:userId/profile
  app/controllers/user/UserProfile.controller.ts
Labels: Documentation

#34 Fix/resigning and discord disconnect
  app/controllers/game/GameApplication.controller.ts
  app/controllers/user/LinkedAccount.controller.ts
  app/controllers/user/User.controller.ts
  app/repository/EmailOptIn.repository.ts
  app/repository/GameApplication.repository.ts
  app/repository/LinkedAccount.repository.ts
  app/routes/LinkedAccount.routes.ts
  app/routes/User.routes.ts
  app/services/Mail.service.ts
  nodemon.json
  test/helpers.ts
  tsconfig.json
Labels: bug

#32 Maint: Error throws over return statements.
  app/controllers/Email.controller.ts
  app/controllers/authentication/Authentication.controller.ts
  app/controllers/error.controller.ts
  app/controllers/game/Game.controller.ts
  app/controllers/game/GameApplication.controller.ts
  app/controllers/game/LiveGame.controller.ts
  app/controllers/user/LinkedAccount.controller.ts
  app/controllers/user/User.controller.ts
  app/controllers/user/UserAvatar.controller.ts
  app/controllers/user/UserProfile.controller.ts
  app/controllers/user/UserStats.controller.ts
  app/middleware/Auth.middleware.ts
  app/middleware/GameApplication.middleware.ts
  app/middleware/GameSchedule.middleware.ts
  app/middleware/User.middleware.ts
  app/routes/Activity.routes.ts
  app/routes/Auth.routes.ts
  app/routes/Game.routes.ts
  app/routes/GameApplication.routes.ts
  app/routes/GameSchedule.routes.ts
  app/routes/Leaderboard.route.ts
  app/routes/LinkedAccount.routes.ts
  app/routes/Temp.routes.ts
  app/routes/User.routes.ts
  app/routes/contact.routes.ts
  app/routes/handlers/index.ts
  app/routes/health.routes.ts
  app/routes/index.ts
  app/services/Server.service.ts
  app/utils/apiError.ts
  test/user.test.ts
Labels: enhancement

#31 Feature: Delete user support
  app/constants/index.ts
  app/controllers/authentication/Authentication.controller.ts
  app/controllers/game/GameApplication.controller.ts
  app/controllers/game/GameSchedule.controller.ts
  app/controllers/user/LinkedAccount.controller.ts
  app/controllers/user/User.controller.ts
  app/models/User.ts
  app/repository/User.repository.ts
  app/routes/Auth.routes.ts
  app/routes/Temp.routes.ts
  app/routes/User.routes.ts
  app/seeding/GameSchedule.seeding.ts
  app/services/Auth.service.ts
  package.json
  test/gameSchedule.test.ts
  test/user.test.ts
Labels: enhancement

#42 Documenting the second endpoint in UserProfile.controller.ts
  app/controllers/user/UserProfile.controller.ts
  app/controllers/user/UserStats.controller.ts
Labels: Documentation

#60 Twitch Connection Support
  .env.example
  app/controllers/user/LinkedAccount.controller.ts
  app/controllers/user/UserStats.controller.ts
  app/repository/Activity.repository.ts
  app/repository/EmailOptIn.repository.ts
  app/repository/EmailVerification.repository.ts
  app/repository/Game.repository.ts
  app/repository/GameApplication.repository.ts
  app/repository/GameSchedule.repository.ts
  app/repository/LinkedAccount.repository.ts
  app/repository/PasswordReset.repository.ts
  app/repository/User.repository.ts
  app/repository/UserStatisticsRepository.ts
  app/routes/LinkedAccount.routes.ts
  app/services/twitch.service.ts
  app/types/mailgun.js/process/process.d.ts
  app/utils/logger.ts
  package-lock.json
  package.json
  test/linkedAccount.test.ts
  test/user.test.ts
  tslint.json
Labels: enhancement

#73 feat: support for applying to games via a Twitch id
  app/controllers/game/Game.controller.ts
  app/controllers/game/GameApplication.controller.ts
  app/repository/Game.repository.ts
  app/routes/GameApplication.routes.ts
  package.json
  test/helpers.ts
Labels: enhancement
